# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField(default=-1)),
                ('sender_fn', models.CharField(blank=True, max_length=100)),
                ('recipient', models.IntegerField(default=-1)),
                ('recipient_fn', models.CharField(blank=True, max_length=100)),
                ('read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_user', models.IntegerField(default=-1)),
                ('start_user_fn', models.CharField(blank=True, max_length=100)),
                ('second_user', models.IntegerField(default=-1)),
                ('second_user_fn', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_reply', models.DateTimeField(blank=True)),
                ('last_message', models.TextField(blank=True)),
                ('job', models.IntegerField(blank=True, default=-1)),
                ('group', models.BooleanField(default=False)),
                ('group_ids', models.TextField(blank=True)),
                ('group_names', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Thread'),
        ),
    ]
